### ISSUE TITLE
Boutons inactifs sur la page d'admin

### ISSUE THREAD

**Issue by BenTotoro** [assobug/smswall#1]
Sur l'écran d'admin, les boutons de modération pour faire apparaitre oudisparaitre un message sur le mur ne changent pas d'état quand on clique dessus. On doit raffraichir manuellement la page pour voir apparaitre les modifications.
De même, le bouton "info bulle" ne fonctionne pas

**Comment by Dweez** [comment]
Bonjour,
Dans les 2 cas, c'est Pusher et la communication websocket qui ne fonctionne pas. Il faudrait vérifier la configuration de l'application Pusher ainsi que les messages sur la console de debug. L'url doit ressembler à ça : 

https://app.pusher.com/apps/xxxx/console

(remplacer les xxxx par l'id de votre application Pusher)
cordialement
